In [1]:
# Pandas es una librería de Python esencial para manipular, limpiar y analizar datos de forma fácil.
import pandas as pd

In [3]:
# Creamos un dataframe con los siguientes valores y luego definimos el dataframe como df.
data = {
    "cliente": ["Ana", "Pedro", "Ana", "Maria", "Pedro"],
    "producto": ["Laptop", "Mouse", "Teclado", "Laptop", "Monitor"],
    "precio": [900000, 20000, 50000, 850000, 200000],
    "region": ["Santiago", "Valparaiso", "Santiago", "Concepcion", "Valparaiso"]
}

df = pd.DataFrame(data)

df

  cliente producto  precio      region
0     Ana   Laptop  900000    Santiago
1   Pedro    Mouse   20000  Valparaiso
2     Ana  Teclado   50000    Santiago
3   Maria   Laptop  850000  Concepcion
4   Pedro  Monitor  200000  Valparaiso

In [4]:
# La función df.describe() nos permite conocer los valores estadísticos de las columnas que sean de valores cuantitativos.
df.describe()

              precio
count       5.000000
mean   404000.000000
std    435694.847342
min     20000.000000
25%     50000.000000
50%    200000.000000
75%    850000.000000
max    900000.000000

In [5]:
# Definimos una variable llamada ventas_region, en donde calculará a través del group by las sumas de las ventas por región.
ventas_region = df.groupby("region")["precio"].sum()

ventas_region

region
Concepcion    850000
Santiago      950000
Valparaiso    220000
Name: precio, dtype: int64

In [6]:
# A través de la mención al dataframe por su abreviación df podemos solicitar el conteo de las veces que aparece cada producto.
df["producto"].value_counts()

producto
Laptop     2
Mouse      1
Teclado    1
Monitor    1
Name: count, dtype: int64

In [7]:
# Para guardar nuestro dataset, se puede ejecutar el siguiente comando para crearlo como archivo ".csv".
df.to_csv("ventas_limpias.csv", index=False)